services:
  # Frontend - Vue 3
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telamonet_frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCH_INTERVAL=500
    depends_on:
      - backend


  # Backend - Laravel
  backend:
    build:
      context: ./backend
    container_name: telamonet_backend
    volumes:
      - ./backend:/var/www
      - backend_vendor:/var/www/vendor
      - backend_storage:/var/www/storage
      - backend_bootstrap_cache:/var/www/bootstrap/cache
      - ./backend/entrypoint.sh:/usr/local/bin/entrypoint.sh
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - app-network

  # Servidor Web para Laravel (Nginx)
  nginx:
    image: nginx:stable-alpine
    container_name: telamonet_nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

  # Base de Datos - MySQL
  db:
    image: mysql:8.0
    container_name: telamonet_dbb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: telamonet
      MYSQL_USER: telamo_user
      MYSQL_PASSWORD: telamo_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # Servidor de Video Llamadas (Signaling)
  signaling:
    build:
      context: ./signaling
    container_name: telamonet_signaling
    ports:
      - "3000:3000"
    volumes:
      - ./signaling:/app
      - signaling_node_modules:/app/node_modules
    networks:
      - app-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: telamonett_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  frontend_node_modules:
  backend_vendor:
  backend_storage:
  backend_bootstrap_cache:
  signaling_node_modules:
