services:
  # Frontend + Web Server (Nginx sirviendo Vue)
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: telamonet_web_prod
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  # Backend (Laravel API)
  backend:
    build:
      context: ./backend
    container_name: telamonet_backend_prod
    restart: always
    volumes:
      - ./backend:/var/www
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    networks:
      - app-network

  # Base de Datos
  db:
    image: mysql:8.0
    container_name: telamonet_db_prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # En prod usar secretos!
      MYSQL_DATABASE: telamonet
      MYSQL_USER: telamo_user
      MYSQL_PASSWORD: telamo_pass
    volumes:
      - mysql_prod_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_prod_data:
